php artisan make:model departemen -mcr
php artisan make:model detail -mcr
php artisan make:model detail_obat -mcr
php artisan make:model detail_tambahan -mcr
php artisan make:model dokter -mcr
php artisan make:model failed_jobs -mcr
php artisan make:model jadwal -mcr
php artisan make:model kamar -mcr
php artisan make:model migrations -mcr
php artisan make:model pasien -mcr
php artisan make:model password_resets -mcr
php artisan make:model pegawai -mcr
php artisan make:model perawatan -mcr
php artisan make:model perbaikan -mcr
php artisan make:model permission -mcr
php artisan make:model permission_role -mcr
php artisan make:model poliklinik -mcr
php artisan make:model presensi -mcr
php artisan make:model regristasi -mcr
php artisan make:model role -mcr
php artisan make:model shift -mcr
php artisan make:model soap -mcr
php artisan make:model users -mcr
