name: Mirror to GitLab Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
 group: git-mirror

jobs:
 git-mirror:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: yesolutions/mirror-action@v0.5.1
       env:
         # REMOTE: 'ssh://git@gitlab.com/<your-gitlab-username>/<your-gitlab-repo-name>.git'
         REMOTE: 'git@gitlab.com:4lend/kurikulumProgrammerPontekindo.git'
         GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY_ED25519 }}
         GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
         DEBUG: "true"
