name: Push to GitLab

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama Anda

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Push to GitLab
      run: |
        # Mengaktifkan agent SSH
        eval "$(ssh-agent -s)"
        ssh-add <(echo "$SSH_PRIVATE_KEY")  # SSH_PRIVATE_KEY adalah secret yang harus Anda tambahkan di pengaturan repository
        
        # Menambahkan host GitLab ke known_hosts
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
        
        # Melakukan push ke GitLab
        git remote add gitlab git@gitlab.com:4lend/kurikulumProgrammerPontekindo.git
        # git remote add gitlab git@gitlab.com:<USERNAME>/<REPO>.git  # Ganti dengan URL repo GitLab Anda
        git push gitlab HEAD:main
